<?php require '_navbar.php'; ?>
<?php require '_ticker.php'; ?>
<?php require '_hero.php'; ?>
<?php require '_dashboard.php'; ?>
<?php require '_needs.php'; ?>
<?php require '_analysis.php'; ?>
<?php require '_vision.php'; ?>
<?php require '_footer.php'; ?>
<?php require '_modal.php'; ?>
